services:
  database:
    image: postgres:16-alpine
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - backend-network


  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend

    restart: unless-stopped

    env_file:
      - path: .env.local
        required: false
      - path: .env.docker
        required: false

    environment:
      DB_HOST: database
      DB_PORT: 5432
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      APP_URL: ${APP_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      SIITEC_CLIENT_ID: ${SIITEC_CLIENT_ID}
      SIITEC_CLIENT_SECRET: ${SIITEC_CLIENT_SECRET}
      SIITEC_AUTHORIZATION_ENDPOINT: ${SIITEC_AUTHORIZATION_ENDPOINT}
      SIITEC_REVOCATION_ENDPOINT: ${SIITEC_REVOCATION_ENDPOINT}
      SIITEC_TOKEN_ENDPOINT: ${SIITEC_TOKEN_ENDPOINT}
      SIITEC_USERINFO_ENDPOINT: ${SIITEC_USERINFO_ENDPOINT}
      SIITEC_USUARIOS_ENDPOINT: ${SIITEC_USUARIOS_ENDPOINT}

    ports:
      - "${BACKEND_HTTP:-20080}:3001"
      - "${BACKEND_HTTPS:-20443}:3443"

    depends_on:
      database:
        condition: service_healthy

    networks:
      - backend-network
      - public


  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend

    restart: unless-stopped

    ports:
      - "${FRONTEND_HTTP:-10080}:80"
      - "${FRONTEND_HTTPS:-10443}:443"

    depends_on:
      backend:
        condition: service_healthy

    networks:
      - public


volumes:
  postgres_data:


networks:
  public:
    name: public
    external: true
  backend-network: